#!/bin/sh
op="test"
L2 "ln -nsf" "test bson as cmd/import latest"
ln -nsf tst/data/bson/ cmd/_data/import/bson/latest

rm -rf .git/hooks;
mkdir .git/hooks;
cd .git/hooks;
ln -nsf ../../cmd/_test/pre-push;
L2 "ln -nsf" ".git/hooks/prep-push"

cd ../../;
L2 "pre-push" "test"
source .git/hooks/pre-push
