module.exports = {
  'CT13': 'Civil and Administrative Tribunal Act',
  'CT14': 'Civil and Administrative Tribunal Rules 2014',
  'CD89': 'Community Land Development Act',
  'CM89': 'Community Land Management Act',
  'CR80': 'Contracts Review Act',
  'CN19': 'Conveyancing Act',
  'CA00': 'Crimes Act [NSW]',
  'CV07': 'Crimes (Domestic and Personal Violence) Act',
  'CL04': 'Crimes Legislation Amendment (Telecommunications Offences and Other Measures) Act',
  'DA05': 'Defamation Act',
  'DF91': 'Dividing Fences Act ',
  'EF18': 'Electoral Funding Act',
  'ED81': 'Election Funding, Expenditure and Disclosures Act',
  'ET17': 'Electronic Transactions Legislation Amendment (Government Transactions) Act 2017 No 25',
  'EP79': 'Environment Planning & Assessment Act',
  'FT87': 'Fair Trading Act',
  'HB89': 'Home Building Act 1989',
  'HB17': 'Home Building Amendment (Compensation Reform) Act 2017 No 28',
  'IN87': ' Interpretation Act',
  'LG93': 'Local Government Act',
  'PA02': 'Property, Stock and Business Agents Act',
  'PA14': 'Property, Stock and Business Agents Regulation',
  'RP00': 'Real Property Act 1900',
  'SD15': 'Strata Schemes Development Act 2015 No 51',
  'SFD73': 'Strata Schemes (Freehold Development) Act 1973',
  'SM96': 'Strata Schemes Management Act 1996 No 138',
  'SM15': 'Strata Schemes Management Act 2015 No 50',
  'SM16': 'Strata Schemes Management Regulation 2016',
  'WC87': 'Workers Compensation Act 1987',
  'WI98': 'Workplace Injury Management and Workers Compensation Act 1998',
  'Anderson2': 'The Owners – Strata Plan No 82306 v Anderson (2)',
  'Anderson': 'The Owners – Strata Plan No 82306 v Anderson',
  'Shum2': 'The Owners Strata Plan No 30621 v Shum (2)',
  'Shum': 'The Owners Strata Plan No 30621 v Shum',
  'Mullen': 'Mullen v Owners Corporation SP 15342',
  'Melani': 'Melani v The Owners Strata Plan No 22214',
  'Shahbzian': 'Shahbazian v Owners Corporation SP 56466',
  'McElwain2': 'McElwaine v The Owners – Strata Plan No. 75975 (2)',
  'McElwain': 'McElwaine v The Owners – Strata Plan No. 75975',
  'Rosenthal2': 'The Owners – Strata Plan SP20211 v Rosenthal',
  'Rosenthal': 'Rosenthal v The Owners SP20211',
  'Thoo3': 'The Owners Strata Plan 50276 v Thoo',
  'Sahade': 'The Owners - Strata Plan No 62022 v Sahade',
  'Thoo2': 'Thoo v The Owners Strata Plan No. 50276 (No. 2)',
  'Thoo': 'Thoo v The Owners Strata Plan No. 50276',
  'Seiwa4': ' The Owners SP 35042 v Seiwa Australia Pty Ltd [2007] NSWCA 272 ',
  'Seiwa': ' Seiwa Australia Pty Ltd v Owners Strata Plan 25042 [2006] NSWSC 1157 ',
  'Ridis': 'Ridis v Strata Plan No 10308',
  'BL96': 'By-laws for pre-1996 strata schemes',
}
