#!/bin/sh
op="webpack"
L2 "rm -rf   " "htp/cdn"
rm -rf htp/cdn

L2 "npx webpack" "--config cmd/b/dev.pk.js --bail --hide-modules\n"
npx webpack --config cmd/b/dev.pk.js --bail --hide-modules

echo
# L2 "npx webpack done..."
