#!/bin/sh
OP="clean"

L2 "rm" "/packages-lock.json"
rm -f package-lock.json
rm -f .DS_Store
L2 "rm -f" "/.npm"
rm -f .npm
L2 "rm -f" "/node_modules"
rm -rf node_modules
L2 "rm -f" "/htp/cdn/ui (dist js/css)"
rm -rf htp/cdn/ui
