#!/bin/sh
# Usage:LAWS
#
#   cmd/db import law --verbose
#
# Usage:SOURCES
#
#   cmd/db import gmail -g sync
#   cmd/db import doc -g OCR
#
# Usage:MIGRATION
#
#   cmd/db migrate/2018-09 all
#   -> coffee cmd/db.coffee -c migrate/2018-09/migrate/2018-09 -o all

CMD=db

source cmd/init

L2 $1

if [ "$3" = "--law-Export" ]; then
  L2 "using fresh ~/Downloads/law.Export.csv"
  mv ~/Downloads/law-Export.csv cmd/d/import/q/law.csv
  # source cmd/d/sync-test
fi

echo

if [ "$1" = "sync" ]; then
  source cmd/db-sync $2 $3 $4 $5 $6
elif [ "$1" = "snapshot" ]; then
  source cmd/db-snap $2 $3 $4 $5 $6
elif [ "$1" = "md" ]; then
  source cmd/db-md $2 $3 $4 $5 $6  
elif [ "$1" = "--replay" ]; then
  # manually update this while developing
  # coffee cmd/db.coffee migrate/2018-09/migrate/2018-09 -o all $3 $4 $5 $6
  coffee cmd/db.coffee -c import/import -o law --verbose $4 $5 $6  
else
  coffee cmd/db.coffee -c $1/$1 -o $2 $3 $4 $5 $6
fi

if [ "$3" = "--sync-test" ]; then
  source cmd/db-snap argu_cmd tst/data/bson laws
  source cmd/db-snap argu_cmd tst/data/bson tags  
fi

L1 "done...\n"


# ln -s ../../../../src/37.sttc/cms/read
