#!/bin/sh
OP="init"
CWD=$(pwd)
PATH="node_modules/.bin/:${PATH}"


function L1() { echo "\033[0;32m${CMD}\033[0m \t\t${1}"; }
function L2() { echo "\033[0;34m${CMD}/${OP}\033[0m\033[0;36m  \t${1}\033[0m\t${2}\033[0m"; }
function L3() { printf "\033[0;37m${CMD}\033[0m  \t${1}\n"; }


echo

if [ "$1" = '-w' -o "$2" = '-w' -o "$3" = '-w' -o "$4" = '-w' -o "$5" = '-w' -o "$6" = '-w' ] ; then
  clear; fi

if [ "$1" = '-v' -o "$2" = '-v' -o "$3" = '-v' -o "$4" = '-v' -o "$5" = '-v' -o "$6" = '-v' ] ; then
  export LOG_VERBOSE=true; fi


L1 "${1} ${2} ${3} ${4} ${5} ${6}"

if [ "$1" = '-k' -o "$2" = '-k' -o "$3" = '-k' -o "$4" = '-k' -o "$5" = '-k' ] ; then
  L2 "killall " "node\n"
  killall node
  echo
fi


# NAN=\033[0m   # No Color
# WIT=1;37m'
# BLK=0;30m'
# BLU=0;34m'
# LBLU=1;34m'
# LGRN=1;32m'
# CYN=0;36m'
# LCYN=1;36m'
# RED=0;31m'
# LRED=1;31m'
# PPL=0;35m'
# LPPL=1;35m'
# BRN=0;33m'
# YLW=1;33m'
# GRY=0;30m'
# GRY=0;37m'


# OUTPUT="$(ls -1)"
# echo "${OUTPUT}"
