#!/bin/sh
# Usage:
#    cmd/run
#    cmd/run --test --worker

CMD=run
BUILD=;
CDN=;
ENV=dev
WEB=;
WKR=;

source cmd/init

if [ "$1" = "--cmd" ]; then
  ENV=cmd
  WEB=cmd/server;
# elif [ "$1" = "--dist" ]; then
#   ENV=prod
#   BUILD=cmd/dist
# elif [ "$1" = "--test" ]; then
#   ENV=test
#   CDN=;
elif [ "$1" = "--dev" ]; then
  BUILD=cmd/dev;
  WEB=cmd/server;
else
#   CDN=cmd/r/cdn
  WEB=cmd/watch;
fi

export ENV=$ENV
L1 "-env ${ENV}"

# if [ "$2" = "--worker" ];
#   then WKR=cmd/r/worker;
# fi



if [ "$BUILD" != "" ]; then source $BUILD; fi
if [ "$CDN" != "" ]; then source $CDN; fi
# if [ "$WKR" != "" ]; then source $WKR --env $ENV & fi
if [ "$WEB" != "" ]; then source $WEB; fi
