#!/bin/sh
# Usage:
#    cmd/run
#    cmd/run --test --worker

CMD=run
BUILD=;
CDN=;
ENV=dev
WEB=cmd/server
# WKR=;

source cmd/init

# if [ "$1" = "--dist" ]; then
#   ENV=prod
#   BUILD=cmd/b/dist
# elif [ "$1" = "--test" ]; then
#   ENV=test
#   CDN=;
# elif [ "$1" = "--dev" ]; then
#   BUILD=cmd/b/dev;
# else
#   CDN=cmd/r/cdn
    WEB=cmd/watch;
# fi

L1 "${ENV}.env"

# if [ "$2" = "--worker" ];
#   then WKR=cmd/r/worker;
# fi

if [ "$BUILD" != "" ]; then source $BUILD; fi
if [ "$CDN" != "" ]; then source $CDN; fi
# if [ "$WKR" != "" ]; then source $WKR --env $ENV & fi
if [ "$WEB" != "" ]; then source $WEB --env $ENV; fi
