#!/bin/sh
CMD="CMD/test"
source cmd/_build/init
L1 "start"

L2 "template"
source cmd/_test/template
# L2 "${T} \n" "\n--DONE-\n"

# if $T !=''
L2 "server"
source cmd/_test/server
# L2 "${T} \n" "\n--DONE-\n"
# fi
