#!/bin/sh
OP="watch"

## MUST RUN cmd/run --dev for new layout.hbs 
# source cmd/dev

L2 "nodemon  " "server/index.js -w server -w pl8 -e env,js,hbs --quiet"
nodemon server/index.js -w server -w pl8 -e env,js,hbs --quiet 
