#!/bin/sh
CMD=CMD/db
op=sync
OUT=tst/data/bson
DB=argu_test

L2 "mongodump" "${DB}.tags\n"
mongodump -h localhost -d $DB -o $OUT -c tags
mv $OUT/$DB/tags.bson $OUT/tags.bson
echo
L2 "mongodump" "${DB}.laws\n"
mongodump -h localhost -d $DB -o $OUT -c laws
mv $OUT/$DB/laws.bson $OUT/laws.bson

rm -rf $OUT/$DB
